name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linter:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: bundle install
      - name: Yarn update
        run: yarn install --check-files
      - name: Run linting without autocorrect
        run: bundle exec rake "lint_and_format[disableautocorrect]"
