name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 1
      - name: Yarn update
        run: yarn install --check-files
      - name: Webpacker workaround
        run: bundle exec rake webpacker:compile
      - name: Run tests
        run: bundle exec rake test
