name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Configure webpacker
        run: rails webpacker:install
      - name: Run linting without autocorrect
        run: rails test
